- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/RawCommandServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
Now the RawCommandServerDefinition support for providing a language id
in addition to extension for language servers which has different id
than the extension.
Also the Initialized message is not send to language server once the
client finishes the initialization since some language servers depends
on it.
Add support for STS4 Language server
> Add support for language id and initialized message

- src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
Add support to reset the language server wrapper. because today if the language server timeouts you need to restart the IDE to get it started again. Some time when the system is busy the language server might timeout. Therefore i have added a new menu item to the language server widget to reset the LSP wrapper so than without restarting the IDE, you can reopen your editor which will start the language server back.
By resetting the language server the user can restart it by opening the file editor again.
> Add support for resetting a failed or timed out language server

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
In addition to extension, file name pattern support is added. The first
priority is given for extension and then for the file name pattern when
resolving server definitions.
To be able to register the language server based on file name pattern like "application.*\.properties" for Spring Boot property file for example.
> Add support for file name patterns for server registration

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/ServerListener.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/MessageHandler.java
When adding support for certain language servers, there is a need to receive server notifications. For example if the client needs to initially send a didChangeConfiguration then we need to wait until the server is initialize according to https://microsoft.github.io/language-server-protocol/specification#initialize. This server listener will help to receive such notifications from the server.
Right now it only support **InitializeResult** message, but the design can be extended support more notifications without breaking the backward compatibility.
> Add initial support for listening to server responses

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
Idea use virtual files for code snippets which are marked as
LightVirtualFile. These files are not part of the LS workspace.
These kind of file editors are used in TestNG Run Configuration for
example.
Fix for https://github.com/ballerina-platform/lsp4intellij/issues/66
> Fix NPE when trying to open virual files which doesn't exist

- src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
When supporting custom LSP extensions, the developer needs more accessibility for the client components. This PR updates access modifiers of few such components.
> Change access modifiers

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/utils/ApplicationUtils.java
Fix "Can't remove document listener" by removing some unwanted document
listener removals on connected editor. This also fixed the issue of LS
error when opening lot of files while the LS is starting.
> Fix "Can't remove document listener" issue

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
When creating lookup item we need to provide the lookup object and then
set the lookup string.
When processing text edit the replace must be perform if the range length
is not equal to newText length.
> Fix completion insertion and caret positioning

- src/main/java/org/wso2/lsp4intellij/contributors/inspection/LSPInspection.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
Add a file support check in addition the extension check to avoid passing down null virtual files.
> Fix NPE at LSPInspection when the virtual file is null.

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/requests/FileEventManager.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
When a file is changed, the change message is sent to all LS wrappers
from all windows. With the fix now it only send to LS wrappers which
are connected to the projects the changed file belongs to.
> Fix triggering LS from different windows

- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/ArtifactLanguageServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/ExeLanguageServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/RawCommandServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
With the previous implementation when supporting for multiple language id
which are not same as the ext we need to define multiple language server
definitions which cause multiple language servers to start.
With new implementation we can support for multiple languages with one
server. This also enable proper language id passing when using
extension patterns.
@NipunaRanasinghe i think this PR is really important for us since this is a breaking change if we plan this after 1.0.0
Example usage:
```
Map<String, String> langMapping = new HashMap<String,String>
langMapping.put("java", LANG_ID_JAVA)
langMapping.put("yaml", LANG_ID_YAML)
langMapping.put("yml", LANG_ID_YAML)
langMapping.put("xml", LANG_ID_XML)
langMapping.put("properties", LANG_ID_PROPERTIES)
RawCommandServerDefinition def = new …
```
> Enhance support for language id passing when document open

- src/main/java/org/wso2/lsp4intellij/contributors/LSPCompletionContributor.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
When a LS takes lot of time for completion request the IDE freezes due to the fact the IDE cannot cancel that request according to the previous implementation. This cause the completion while typing to cause UI freeze while typing letters. With the fix the request is cancelled if the current progress is cancelled by the IDE. Also added support for providing a PsiElementPattern by the consumer so that the Contributions can be targeted to specific locations in the while by sub classing this contributor to suit consumer language.
> Add support for async and cancellable completion proposal contributor

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
This PR fixes few issues related to language server exception handling and add minor improvements.
Fixes #47.
> Improve language server wrapper implementation

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/requests/WorkspaceEditHandler.java
When applying multiple text edits in a single file,  all the other edit ranges will be invalid after the very first edit, since the document is changed after the first text edit apply. This PR adds a fix by creating a sorted edit list based on the insertion position and the edits will be applied from the bottom to the top of the document.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/15653.
> Fix multiple text edit handling for a single document

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
Currently, when we provide add LS definition using `addServerDefiniton()`, those definition will be added in application-level and will be consumed by the all the opened projects.
This PR introduces support for adding project-specific server definitions, where you can pass the project instance as a parameter.
This will add the support of using different versions of a particular language server for different projects.
> Add project-level server definition support

- build.gradle
- src/test/java/org/wso2/lsp4intellij/utils/FileUtilsTest.java
Hi,
As suggested I have written some tests for `org.wso2.lsp4intellij.utils.FileUtils` with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
> Add unit tests for `org.wso2.lsp4intellij.utils.FileUtils`
> Improve coverage
> JDK 8
Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.
> Add unit tests for org.wso2.lsp4intellij.utils.FileUtils

- src/main/java/org/wso2/lsp4intellij/actions/LSPReformatAction.java
- src/main/java/org/wso2/lsp4intellij/actions/LSPShowReformatDialogAction.java
1.  add reformat selection to LSPReformatAction
2.  do not pop out show reformat dialog twice
> 1.  If user has selection in editor when using lsp reformat, our plugin still reformat the whole file for the user. But in Java, it will only reformat selection code.  In order to have the same user experience,  I suggest this pull request
> 2.  If user clicked "cancel" after "Show Reformat File Dialog", our plugin will still pop up the dialog again, as in this [line](https://github.com/ballerina-platform/lsp4intellij/blob/b0e378e60be5a27e7ed1a53ac0076f902fea8ac2/src/main/java/org/wso2/lsp4intellij/actions/LSPShowReformatDialogAction.java#L69)
> 1. If user has selection in editor when using lsp reformat, our plugin will only reformat selection
> 2. If user clicked "cancel" after "Show Reformat …
> tiny change to Reformat , so that it will be the same user experience as Java in Intellij IDEA

- README.md
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManagerBase.java
- src/main/java/org/wso2/lsp4intellij/utils/OSUtils.java
$subject since in mac os, goto defs/refs and hover should be triggered when pressing command key (not CTRL).
> Replace "ctrl" key functionality to "command" key in mac os

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
Per https://github.com/ballerina-platform/lsp4intellij/issues/121, command-clicking on a symbol should "_jump_ to definition", if implemented by LSP.
Instead, currently it only selects the target range in the editor, without navigating to it.
Navigation to the target range on ctrl+click is common in other plugins for IntelliJ, as well as other editors like VS Code. We're just enabling it here.
Additionally, we remove "selection" for the target range, which provides an eyesore if the selection is large (e.g. when the target is a block …
> Navigate to line/column in goto definition/references

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
This PR introduces language server restart support. So you can simply try to restart your failed language server using the restart action available in language server status icon.
Please refer the following example.
> Add language server restart support

- src/main/java/org/wso2/lsp4intellij/contributors/symbol/LSPNavigationItem.java
- src/main/java/org/wso2/lsp4intellij/contributors/symbol/LSPSymbolContributor.java
This fixed handling of duplicate names in symbol list if two items
have the same name.
Before when we have duplicate names the items shown is 2 * number duplicates. This fixes it.
> Update symbol contributor to new API

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/MessageHandler.java
Add support for shutting down language server when IDE window is closed and IDEA jvm is forcefully stopped.
> Add proper shutdown support when closing IDE window

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java
- src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPIconProvider.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/extensions/LSPExtensionManager.java
- src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
Add support for customize icons from LS client implementation (enhanced)
- Fix all the places where default static implementation was used for Icon
provider.
- Moved the IconProvider to ExtensionManager instead of the
ServerDefinition
> Add support for customize icons from LS client implementation.

- src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameHandler.java
> 1. Fix the bug of doing nothing when using rename from menu ( or popup menu) Refactor->Rename.  Please check the attached gif. The first rename was done by Shift+F6
> if the user click rename from menu, our plugin will do the rename
> When using rename from menu, the editor lost focus, so this line below will be false. It is easy to find out when debugging the code
`if (editor.getContentComponent().hasFocus())`
> openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+12-b304.10)
OpenJDK 64-Bit Server VM (build 11.0.3+12-b304.10, mixed mode)
$ ./clangd --version
clangd version 8.0.0 (tags/RELEASE_800/final)
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.
> fix rename bug, editor does not hasFocus when using rename from menu

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/extensions/LSPExtensionManager.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
This change introduce a new method in LSPExtensionManager so that
implementors can use to control which files should be connected to LS
based on their content or PsiFIle Language.
> Add support for file content based connection to LS

- src/main/java/org/wso2/lsp4intellij/contributors/label/LSPDefaultLabelProvider.java
- src/main/java/org/wso2/lsp4intellij/contributors/label/LSPLabelProvider.java
- src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java
- src/main/java/org/wso2/lsp4intellij/extensions/LSPExtensionManager.java
- src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
The default label provider is used by when no custom label
provider is provided.
> Add LabelProvider for LPS elements such as symbols.

- src/main/java/org/wso2/lsp4intellij/contributors/fixes/LSPCommandFix.java
> Our plugin could not show quick fix from clangd with LSPCommandFix disabled
> After I enabled it, quick fix (Alt+Enter) is ok now. 
> openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+12-b304.10)
OpenJDK 64-Bit Server VM (build 11.0.3+12-b304.10, mixed mode)
$ ./clangd --version
clangd version 8.0.0 (tags/RELEASE_800/final)
> LSPCommandFix should be enabled

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/requests/HoverHandler.java
- src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
- enabled HTML formatting for all content since LSP spec is now sending
markup content
- use a textpane with JB html kit to style the documentation
- add support for lanuguage like java which doesn't inherit from plain
text language.
- add support for open source files from links in quick doc hover
> Add support for quick doc hovers (support for opening files)

- src/main/java/org/wso2/lsp4intellij/contributors/symbol/LSPSymbolContributor.java
- src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java
Add support for scoping the symbol results using IntelliJ default scope options.
Now the open symbol popup's default scoping options can be applied to LSP results as well.
> Add support for scoping symbols

- src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java
- src/main/java/org/wso2/lsp4intellij/utils/ApplicationUtils.java
This fix will make sure the file index is not accessed while PSI file
events are being processed. This is a prohibited action in 2019.3
> Fix random error in 2019.3

- README.md
Fixes the link in
> 1. Instantiate a concrete subclass of the **LanguageServerDefinition**.
> fix broken link in README.md.

- src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java
Fix for the following compatibility issue
```
Compatibility problems (1): 
#Access to unresolved field com.intellij.icons.AllIcons.Nodes.DataSource : Icon
Method org.wso2.lsp4intellij.contributors.icon.LSPDefaultIconProvider.getCompletionIcon(org.eclipse.lsp4j.CompletionItemKind kind) : javax.swing.Icon contains a *getstatic* instruction referencing an unresolved field com.intellij.icons.AllIcons.Nodes.DataSource : javax.swing.Icon. This can lead to **NoSuchFieldError** exception at runtime.
```
When verified against: IC-201.6668.121
> Fixed compatibility issues with upcoming IJ release

- build.gradle
- src/main/java/org/wso2/lsp4intellij/contributors/psi/LSPPsiElement.java
- src/main/java/org/wso2/lsp4intellij/contributors/symbol/LSPSymbolContributor.java
This updates the build to target IDEA 2020.1. I'm not sure if we want to leave the `build.gradle` as-is or update it to 2020.1 as I have in this PR. There's certainly value in updating it to verify that the build actually compiles with a recent version of IntelliJ. If we want to ensure cross-IntelliJ compatiblity, we should probably update the CI job to deal with that in some way.
I've titled this PR as `WIP` as the `FileUtilsTest` is failing for me. However, HEAD doesn't build for me for other reasons, so if it passes on CI I'd be ok with moving forward.
```
> Task :test
org.wso2.lsp4intellij.utils.FileUtilsTest > initializationError FAILED
org.objenesis.ObjenesisException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.IllegalAccessError
9 tests completed, 1 …
```
> Update for IDEA 2020.1

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
isWillSaveWaitUntil uses many methods that may return nulls and a lot of null-checks. Let's move this null-check to java8 Optional feature.
Reduce NPEs
> Null-safe Optional

- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
I'm not sure if this is the right way to go about this, but we likely want some way of customizing the highlighting of LSPAnnotator. Extending LSPAnnotator and customizing its behavior with this new method, `modifyCreatedAnnotation()`, seems to make this work quite easily. Though, again, I'm open to a better way of accomplishing this.
For context, here is how I'm using this -
```scala
class HaskForceLSPAnnotator extends LSPAnnotator {
override def modifyCreatedAnnotation(annotation: Annotation): Unit = {
GhcMessageType.of(annotation.getMessage).foreach {
case GhcMessageType.NotInScope =>
annotation.setHighlightType(ProblemHighlightType.LIKE_UNKNOWN_SYMBOL)
case GhcMessageType.CouldNotFindModule =>
annotation.setHighlightType(ProblemHighlightType.LIKE_UNKNOWN_SYMBOL)
}
}
}
```
> Make LSPAnnotator more extensible

- src/main/java/org/wso2/lsp4intellij/contributors/symbol/LSPSymbolContributor.java
This will add support to pass in what is ready typed in the Symbols Popup filter as the query to symbols request.
This is valuable when LS will limit the number of symbols that are returned for performance reasons. For example STS4 LS will only return 50 symbols in a single invocation. So you will need to narrow down the search query to get the symbols you need. 
This change will help such LS implementations.
> Add support for passing in symbol pattern as a query

- src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java
It is not necessary to open the editor when the file changes the writable status, prevent this to happen when the file uri doesn't change
> If your lsp protocol changes the writable status of specific files, IntelliJ opens one editor per file changed. This is very annoying for the users
> Check if the file name change before opening the editor
> n/a
> N/A bug fixed, no user experience changed
> 
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted …
> Do not reopen files when writable status changes

- src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
1. closes #210 - checks whether actions are received (i.e. are null) and not assuming that returns an empty list
2. responds with null if the dialog/notification is closed without a choosing an action - according to LSP Spec (3.15).
3. Additionally this PR introduces the ability to make showMessage/+Request less intrusive via non-modal Notifications.
> fix NPE #210 and respond according to spec; propose less intrusive showMessage/Request() ui

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
closes #203. Allows to startup the projects server connections (previously added via `addServerDefinition(..)` ) without the need to open an Editor.
added  `initProjectConnections(@NotNull Project project)` to the `IntelliJLanguageClient`.
The method iterates over the datastructure to find the serverdefinition keys for this project and try to start a wrapper.
For codereuse the `LanguageServerWrapper` initialization inside of `connect(Editor)` was refactored into another method.
> Enhancement: Starting connections without opening an Editor first

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
Fixes #208 
Use the projects tabsize and sets the corresponding property on the FormattingOptions object before making a reformat request.
> Add tabsize to FormattingOptions

- build.gradle
Fixes #207
See https://github.com/eclipse/lsp4j/releases/tag/v0.10.0 for the lsp4j changelog. All breaking changes in this release are related to DAP, so nothing other than bumping the library version should need to be done.
> Bump lsp4j version to v0.10.0

- src/main/java/org/wso2/lsp4intellij/listeners/LSPEditorListener.java
happens e.g. in preview editors like in references or commit dialog;
limits usage of lsp features to editors which are shown in tabs -> EditorKind.MAIN_EDITOR
closes #229
> fixes removal of listeners in case another editor w/same uri is closed

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/ServerStatus.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/contributors/LSPCompletionContributor.java
- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
- src/main/java/org/wso2/lsp4intellij/contributors/fixes/LSPCodeActionFix.java
- src/main/java/org/wso2/lsp4intellij/contributors/fixes/LSPCommandFix.java
- src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java
- src/main/java/org/wso2/lsp4intellij/editor/DocumentEventManager.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManagerBase.java
- src/main/java/org/wso2/lsp4intellij/utils/ApplicationUtils.java
- src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
this is my refactoring for fixing problems with multiple open editors (split editor, preview editors...) (for example mentioned in #142 and #231)
unfortunately using a many-to-one (implicit)-mapping from editor to editorManager turned out to be the wrong abstraction, as you can have multiple editors open for the same file in intellij. i solved this by using a set of EditorEventManagers per uri and a one to one relationship from editors to EditorEventManager. This lead to problems in separating documentEvents, which are still somewhat intertwined with EditorEvents.
it's still very rough, as i tried to maintain as much as possible API-compatibility. It would be great if you can comment on how much this is needed. Also general comments are welcome.
I will test change this internally to find …
> fixes multiple problems with split / preview editors

- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
deprecations can now be rendered. This is a feature of [lsp 3.15](https://microsoft.github.io/language-server-protocol/specification#diagnostic).
also fixes #200
Note that i associated LSP-"Information" with IJ-"Weak warning" and LSP-"hint" with IJ-"information", as "hint" in vscode is rendered invisible like Information is in Intellij. This is just a different choice of semantics.
> add Deprecations

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/editor/DocumentEventManager.java
Signed-off-by: Kathryn Kodama <kathryn.s.kodama@gmail.com>
Fixes #249 
- Adds `CodeActionLiteralSupport` capabilities
- increments version prior to setting text document version so that code actions are applied and do not result in `Edit version %d is older than current version %d` error
> Fix versioning error and add CodeActionLiteralSupport

- README.md
- build.gradle
- resources/plugin.xml.example
- src/main/java/org/wso2/lsp4intellij/actions/LSPReferencesAction.java
- src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/ServerOptions.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/contributors/LSPCompletionContributor.java
- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
- src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java
- src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameHandler.java
- src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameProcessor.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/listeners/LSPTypedHandler.java
- src/main/java/org/wso2/lsp4intellij/statusbar/LSPServerStatusWidget.java
- src/main/java/org/wso2/lsp4intellij/statusbar/LSPServerStatusWidgetFactory.java
- src/test/java/org/wso2/lsp4intellij/utils/FileUtilsTest.java
this resolves #190, #189, #184
and prepares for #192, #175
NOTE: This also raises the minimum IJ version to 2021.1 and Java version to 11!
I've also adjusted parts of the documentation, which i hope is clearer now.
Note that the plugin.xml-setup is now more complex, as all the listerners get to be defined in the xml instead of IntellijLanguageClient. I've added an example to cover that. Also i deprecated the Plugin-Components approach in the documentation  (which should still work however)
Note that i did not test all changes, as my Language server does not cover all use cases. I believe however that these changes are minor and hopefully work.
To cover #175 & #192 we need to use Services, which should be easy to do however, they just need to be registered in plugin.xml. We also probably …
> Fix deprecations

- src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
> Prevent a possible exception when publishing diagnostics, fixes #281 
> add a null check
> fix null pointer exception that can occur when opening / closing files while the LSP is running
OSX
> prevent null pointer exception if no managers are found when publishing diagnostics

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
> resolves #286 to ensure that plugins can use the lsp without using the status widget
> ensure the status widget is treated as optional in the codebase
> getWidget method now returns an optional
> OSX
> make getWidget() return an optional and handle this appropriately where this method is used

- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
> fix for #288 
> prevent null pointer exception that occurs when opening / closing files
> null check on LanguageServerWrapper
> OSX
> prevent null pointer exception with languageServerWrapper when opening / closing files

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
> fixes #291 
> Ensure that if a project is closed and reopened the lsp still connect properly
> clean project related server definition when a project is closed
> OSX
> clean up project related extToServerDefinition when closing a project

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/utils/ApplicationUtils.java
> fix #282, I have been testing without this restart mechanism for the EXECUTOR_SERVICE and have not found any downside to doing so
> prevent RejectedExecutionException
> remove unnecessary restart mechanism
> OSX
> prevent RejectedExecutionException by removing mechanism to restart executor server during LanguageServer stop

- src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
> fixes #294 
> prevent NPE
> extra null check in didOpen method so it matches didClose
> prevent NPE of getOpenClose() tristate boolean by converting null to false

- src/main/java/org/wso2/lsp4intellij/editor/DocumentEventManager.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
> fixes #304 
> ensure files that do not have an extension can be properly handled by the lsp
> for files that do not have an extension treat the extension as a empty string instead of null so that it can be handled properly by the lsp
> ensure lsp can support files without an extension

- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/listeners/LSPTypedHandler.java
- src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
* Fixes an NPE introduced by #274. The new API now returns an `Either` that can be null and we were not checking for it. Looks like other places correctly check for it.
* Fixes #276: Fixes the trigger character handler that broke on #251 (they even added the missing class as a top level import but probably forgot to commit the method call).
* Fixes #300: Removes deprecated calls to `AnnotationBuilder.createAnnotation`. It's not clear to me how to get an `Annotation` object after the API has been deprecated, so I followed another part of the code base: https://github.com/ballerina-platform/lsp4intellij/blob/6ed1ed4adb6a5e6ebe1db0459fc0db015186d529/src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java#L1466-L1467
* Fixes a small one-off bug when the LSP sends a range that …
> Fix trigger characters and NPE on completion

- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
There was no way for users to provide their own values for this object. Now they can by simply overriding this new method.
Feel free to modify this PR directly before merging.
Increase flexibility.
Usage is as follow:
```kotlin
class MyServerDefinition(ext: String, command: Array<String>) :
RawCommandServerDefinition(ext, command) {
override fun customizeInitializeParams(params: InitializeParams) {
val applicationInfo: ApplicationInfo? =
ApplicationManager.getApplication().getService(ApplicationInfo::class.java)
val ideVersion: String? = applicationInfo?.fullVersion
val ideName = ApplicationNamesInfo.getInstance().fullProductName
params.clientInfo = ClientInfo(ideName, ideVersion)
}
}
```
> Allow users to customize the InitializeParams object for the "initialize" method

- src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
> Deprecate getInitializationOptions() API and fix other deprecated usages

- src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/editor/DocumentEventManager.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManagerBase.java
- src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java
Wrap value as a new hash set to avoid the concurrent modification
Also protected the modifications to the sets stored in the map as there were race conditions involved with the current implementation.
There can be concurrent modification events to the sets stored in as the values in the map, even though the map itself is a ConcurrentHashMap.
Additionally, if multiple threads are operating on the concurrent hash map the values which no longer exist could attempt to be removed.
Adding the synchronization to any access to the map and working on copies of the values prevents both the above issues.
Prevent concurrent modification exceptions and NPEs when operating on editor maps.
Synchronization on access to the map and operation on copies of the data.
> Wrap value as a new hash set to avoid the concurrent modification

- README.md
Resolves #307
Just add some example  for custom initialization options
> docs: Add example for custom initialization options #307

- src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
In Hover Request the server can respond with either a boolean or HoverOptions. In the current implementation in case when the server responds with HoverOptions the Either.left is `null` and this causes a NullPointerException.
The goal is to correctly handle response from the server.
A simple reverse of the order of `||` check will prevent the NPE from happening.
N/A
Fix NPE on Hover Request when the response contains HoverOptions.
N/A
N/A
N/A
N/A
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
N/A
N/A
N/A
N/A
N/A
> Fix NPE when handling Hover Request

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
> Today I pulled master, build lsp4intellij jar and added to my project.
I got yellow icon and my plugin was not working.
After analysis I found that with #312 pull request was changed LanguageServerWrapper#getInitParams().
> It would be good that NPE would not be thrown
> delete deprecated code
> Removed deprecated code related to rootUri
> N/A
> N/A
> N/A
>  N/A
- I was not able to find any effected unit test
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> It is not thorowing NPE
> List any other related PRs: #312 
> N/A
> N/A
> N/A
> Remove deprecated rootUri as it causes NPE

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
Send ClientInfo about the client initializing a connection to the LSP server.
I collect the information about product name and product version from IntelliJs ApplicationInfo class.
This change resolves in this clientInfo in the initialize request:
```
"clientInfo": {
"name": "IntelliJ IDEA",
"version": "2022.1.4"
}
```
> feat(ClientCapabilities): Set ClientInfo in initialize request

- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
The name field in the WorkspaceFolder entity is not optional in the LSP specification. Therefore, we should set the field to the current project's name. Some LSP implementations rely on this field, as it is not optional. I wonder why there is a constructor in LSP4J without the name...
> Set WorkspaceFolder name in InitializationParams

- src/main/java/org/wso2/lsp4intellij/requests/HoverHandler.java
This resolves empty hover popups being shown when an empty value is present in the MarkupContent. 
In the EditorEventManager is a check for null or emptyString which is not resolved to true in the current implementation as an empty markdown value resolves to "<html></html>". Therefore, an empty popup is shown.
https://github.com/ballerina-platform/lsp4intellij/blob/72a2879d8279dc86da79200ccb663e97c86163e7/src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java#L740-L746
> fix empty HoverElement when empty markdown value received

- src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
$subject. This should fix the instances where the client ends up sending negative column values to the LS, which is an LSP violation as the per the spec.
> Link to the PR for changes to the training content in …
> Fix column calculation during offset to LSP position conversion

- src/main/java/org/wso2/lsp4intellij/statusbar/LSPServerStatusWidget.java
Example stack trace on Android Studio Flamingo when closing project:
`java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.wm.StatusBarWidgetFactory.disposeWidget(com.intellij.openapi.wm.StatusBarWidget)" because "factory" is null
at org.wso2.lsp4intellij.statusbar.LSPServerStatusWidget.lambda$dispose$0(LSPServerStatusWidget.java:115)
at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
at …
> Fix NPE in status widget dispose

- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
- src/test/java/org/wso2/lsp4intellij/utils/FileUtilsTest.java
> Fixes `NullPointerException` in FileUtils.java. 
Bug details: https://github.com/ballerina-platform/lsp4intellij/issues/328
> Encode filepath before converting them to URI.
> Encode special characters in filepath before converting path to URI

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
"Go to definition" completely breaks down when using LSP4IntelliJ for connecting to the [Zig Language Server](https://github.com/zigtools/zls).
The source of this issue was that ZLS returns a `LocationLink` instead of a Location in the reply to the `definition` call, and this causes lsp4intellij to "spazz out", and open dozens of unrelated editors.
Implement a basic way for interpreting `LocationLink` without affecting too much of the codebase.
`LocationLink` contains all of the information necessary to construct a `Location` object, so I just added a trivial conversion to the `EditorEventManager.requestDefinition` method.
I have personally experienced this problem while developing a Zig language plugin for intellij using this library.
Once the fix was implemented in a local fork, go to …
> Fix go to definition when server returns LocationLink

- src/main/java/org/wso2/lsp4intellij/requests/HoverHandler.java
The Hover feature uses a fixed font size that is not configurable, and doesn't scale with the editor font size.
Make the Hover display text which appears similar to the rest of the UI, such as completions and action menus.
I used the `UiUtil` class (already used here to get the dark/light mode) to instead get the label font and generate corresponding HTML styles. Below is a demonstration of Darcula and IntelliJ Light themes:
This is an example with `.AppleSystemUIFont` size 18. I can't figure out what the original font or size was prior to this change, as it wasn't configurable.
A user that needs to change their font or increase their font size for accessibility will see their font size reflected in the hover similar to how it appears in the rest of the IntelliJ UI.
Documentation hover …
> Fix: Hover font should use editor font settings

- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
When issuing a diagnostic with a particular range, annotations are only displayed for that range.
When issuing a code action for a diagnostic with a particular range, the annotation is applied to the whole document.
A code action should only cause the range specified by the action to be underlined with an error.
Use the `AnnotationBuilder::range` parameter to forward the `QuickFixInfo.textRange` from the actions to the newly created annotation. In order to avoid an IllegalStateException from setting the range twice, use a variable to only set it once.
A user which has a server which provides code actions will have not have their whole document highlighted as an error each time a code action is usable.
Fix bug where code actions highlighted entire file as an error
- Unit tests 
> Code …
> Fix: Code action annotations lose range

- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
Currently in order to compute code actions, the user must move their cursor within a diagnostic, and wait for the cursor debounce before selecting the code action.
Code actions should be computed immediately after obtaining diagnostics, without waiting for the user to move the cursor within the diagnostic.
I added a call to EditorEventManager::requestAndShowCodeActions() inside the isDiagnosticsSyncRequired() branch in LSPAnnotator. This should mean that each time after the diagnostics are updated, the code actions valid for the current cursor will be checked.
This operation has some delay (as it is making a request to the language server) so the results must be processed on a subsequent LSPAnnotator run. I had some issues with what appeared to be the DaemonCodeAnalyzer still running at …
> Fix: Request code actions immediately after diagnostics arrive

- src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/actions/LSPQuickDocAction.java
- src/main/java/org/wso2/lsp4intellij/actions/LSPReformatAction.java
- src/main/java/org/wso2/lsp4intellij/actions/LSPShowReformatDialogAction.java
- src/main/java/org/wso2/lsp4intellij/client/connection/ProcessStreamConnectionProvider.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/editor/DocumentEventManager.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManagerBase.java
- src/main/java/org/wso2/lsp4intellij/listeners/LSPEditorListener.java
- src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java
- src/main/java/org/wso2/lsp4intellij/listeners/LSPListener.java
- src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
Core changes are (I could be wrong on any of this, so please be careful when you review this... you can follow my investigation and train of thought in #344):
* (https://github.com/ballerina-platform/lsp4intellij/pull/345/commits/9b2b0557c93dbdb8cbe2b7a6b09925286a44d663) `LSPFileEventManager#fileRenamed` was sending duplicate `didChangeWatchedFiles` notifications.
* (https://github.com/ballerina-platform/lsp4intellij/pull/345/commits/bc9c5ea31c2b0735f3a3620d64b72e58198d24a5) `EditorEventManagerBase#unregisterManager` was not appropriately cleaning up the `Set<EditorEventManager>`.
* This was causing `DocumentEventManager#documentClosed` to not hit the appropriate code path because `EditorEventManagerBase.managersForUri` was not appropriately maintained. (In turns causing the …
> Fixing closing/reopening files

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
Triggering code actions without a diagnostic context currently results in an ```IllegalArgumentException```. This fix will ensure that the corresponding IDE error message is suppressed.
Related to https://github.com/ballerina-platform/lsp4intellij/issues/278
Gracefully handle ```IllegalArgumentException``` within a try-catch block. This error will be thrown when creating a new annotation object to display the relevant code action.
> Suppress the IllegalArgumentException thrown when creating a new annotation

- resources/plugin.xml.example
- src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/ServerWrapperBaseClientContext.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
Adds editor event log tab notifications for LSP messages that display progress update information. Display notifications for start and end of a work done progress. This also fixes the issue https://github.com/ballerina-platform/lsp4intellij/issues/347 that happens due to not supporting LSP progress indication messages.
```createProgress(WorkDoneProgressCreateParams params)```: This method is triggered upon receiving a _**window/workDoneProgress/create**_ request from the language server. It extracts the progress token from the request parameters, which can be either a String or a numeric value. This token uniquely identifies the progress report session. The method then initializes a progress notification item with a default title and an empty message, associating it with the token in a …
> Add IDE notifications for LSP progress update messages

- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
When typing at the start of a document (offset 0), the code completion feature does not capture the initial characters typed. Consequently, accepting a completion suggestion results in it being incorrectly appended to the initially typed text. This fix aims to ensure that suggestions are accurately based on the entire text entered and are inserted correctly. Related to https://github.com/ballerina-platform/lsp4intellij/issues/351
**Change the function** ```public String getCompletionPrefix(Editor editor, int offset)```
In the original implementation, the function scans backwards from the offset until it encounters a delimiter. If no delimiter is found, it returns an empty string. However, at the start of the document where there are no preceding delimiters, this approach results in an …
> Fix code completion issue on the document start offset

- src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/MessageHandler.java
- src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
These fixes will ensure that error diagnostics are displayed upon opening an editor and address the issue of error diagnostics disappearing. Additionally, code actions will be displayed as expected, and error highlights will remain visible when a code action is triggered. Error diagnostics with identical start and end offsets will also be displayed correctly.
Related to https://github.com/ballerina-platform/lsp4intellij/issues/353, https://github.com/ballerina-platform/lsp4intellij/issues/265
1. Added an extra condition in the `didOpen(DidOpenTextDocumentParams params)` function to check if the language server supports file syncing and to trigger the language server's didOpen command. This ensures that error diagnostics are visible upon opening an editor.
2. Removed a condition in the …
> Fix error diagnostics and code actions display issues

- src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
This PR introduces several styling enhancements to improve the visual display of content in the hover box, addressing the issue described in [lsp4intellij#356](https://github.com/ballerina-platform/lsp4intellij/issues/356).
The content within the hover box is processed as HTML. The following improvements have been applied to the HTML code used for displaying hover content:
1. Change the font styles in paragraph, code, and header tags.
2. Add a theme-aware background highlight color to code tags. This color is calculated by inverting the font color and darkening it slightly.
3. Add horizontal padding to the code tags. Since CSS padding does not function inside the hover box, spaces were manually added at the beginning and end of the content in code tags. Code tags that end with a newline …
> Improve the hover content rendering

- src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/RequestManager.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
- src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
This PR adds the code actions resolving feature in LSP to the library. Related to https://github.com/ballerina-platform/lsp4intellij/issues/362
If a returned code action has no workspace edits, we call the code actions resolving endpoint with the initial code action and it will return a new code action with the complete workspace edit.
> Add code action resolving

- src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
- src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/MessageHandler.java
This PR resolves the lagging issues and IDE errors that occur when using the library with IntelliJ versions 2023 and 2024. Related to https://github.com/ballerina-platform/lsp4intellij/issues/364
The root cause of the lag is the checking of each message passed between the server and client. After removing the relevant try-catch block, a null pointer exception occurs for progress notification messages. This issue arises because the return value of the method `public CompletableFuture<Void> createProgress(WorkDoneProgressCreateParams params)` is `null`. After adding a proper type-matching return value, the null pointer error and lagging issue no longer occur.
> Fix lagging issues in the version 0.96.0
