travis.yml
Reverts NipunaRanasinghe/lsp4intellij#2
=> Revert "Add initial travis configurations"

src/main/java/com/github/lsp4intellij/PluginMain.java, src/main/java/com/github/lsp4intellij/client/LanguageClientImpl.java, src/main/java/com/github/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/com/github/lsp4intellij/contributors/fixes/LSPCodeActionFix.java, src/main/java/com/github/lsp4intellij/contributors/fixes/LSPCommandFix.java, src/main/java/com/github/lsp4intellij/contributors/inspection/DummyLSPInspection.java, src/main/java/com/github/lsp4intellij/contributors/inspection/LSPInspection.java, src/main/java/com/github/lsp4intellij/contributors/inspection/LSPInspectionPanel.java, src/main/java/com/github/lsp4intellij/contributors/inspection/LSPInspectionProvider.java, src/main/java/com/github/lsp4intellij/contributors/psi/LSPPsiElement.java, src/main/java/com/github/lsp4intellij/editor/EditorEventManager.java, src/main/java/com/github/lsp4intellij/requests/WorkspaceEditHandler.java, src/main/java/com/github/lsp4intellij/utils/DocumentUtils.java, src/main/resources/META-INF/plugin.xml
=> Add diagnostics and code action support

src/main/java/com/github/lsp4intellij/IntellijLanguageClient.java, src/main/java/com/github/lsp4intellij/client/LanguageClientImpl.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/ArtifactLanguageServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/ConfigurableTypes.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/ExeLanguageServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/RawCommandServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/UserConfigurableServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/com/github/lsp4intellij/contributors/inspection/LSPInspection.java, src/main/java/com/github/lsp4intellij/editor/listeners/EditorListener.java, src/main/java/com/github/lsp4intellij/requests/FileEventManager.java, src/main/java/com/github/lsp4intellij/utils/Utils.java
- $Subject.
- Adds minor improvements and fixes.
=> Improve developer API

src/main/java/com/github/lsp4intellij/IntellijLanguageClient.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
=> Add support for multiple file extensions

src/main/java/com/github/lsp4intellij/editor/EditorEventManager.java, src/main/java/com/github/lsp4intellij/utils/DocumentUtils.java, src/main/java/com/github/lsp4intellij/utils/FileUtils.java
=> Improve stability in windows

src/main/java/com/github/lsp4intellij/contributors/inspection/LSPInspectionProvider.java, src/main/java/com/github/lsp4intellij/editor/EditorEventManager.java
=> Revert diagnostics highlighting strategy

.gitignore, README.md, build.gradle, gradle.properties, src/main/java/com/github/lsp4intellij/IntellijLanguageClient.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/serverdefinition/UserConfigurableServerDefinition.java, src/main/java/com/github/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/com/github/lsp4intellij/contributors/psi/LSPPsiElement.java, src/main/java/com/github/lsp4intellij/contributors/psi/LSPPsiReference.java, src/main/java/com/github/lsp4intellij/requests/WorkspaceEditHandler.java
This PR adds,
- gradle release plugin 
- gradle maven-publish plugin 
- signing plugin
- minor documentation fixes
=> Add release process configurations

README.md, src/main/java/com/github/lsp4intellij/actions/LSPQuickDocAction.java, src/main/java/com/github/lsp4intellij/actions/LSPReformatAction.java, src/main/java/com/github/lsp4intellij/actions/LSPShowReformatDialogAction.java, src/main/java/com/github/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/com/github/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/com/github/lsp4intellij/editor/EditorEventManager.java, src/main/java/com/github/lsp4intellij/editor/EditorEventManagerBase.java, src/main/java/com/github/lsp4intellij/editor/listeners/DocumentListenerImpl.java, src/main/java/com/github/lsp4intellij/editor/listeners/EditorMouseListenerImpl.java, src/main/java/com/github/lsp4intellij/editor/listeners/EditorMouseMotionListenerImpl.java, src/main/java/com/github/lsp4intellij/editor/listeners/LSPListener.java, src/main/java/com/github/lsp4intellij/extensions/LSPExtensionManager.java, src/main/java/com/github/lsp4intellij/requests/HoverHandler.java, src/main/java/com/github/lsp4intellij/requests/ReformatHandler.java, src/main/java/com/github/lsp4intellij/utils/DocumentUtils.java, src/main/java/com/github/lsp4intellij/utils/GUIUtils.java
=> Add formatting and hover support 

build.gradle
This PR adds a minor fix related to the Gradle release plugin.
=> Fix for 0.8.0 release

build.gradle
Update the intellij plugin version
=> Update intellij gradle plugin version to latest

gradle.properties
=> Merge 0.8.0 release branch

README.md, gradle.properties, src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/requests/Timeout.java
This PR adds user API for configuring timeouts of LSP based requests.
Fixes #30.
=> Add timeouts configuration support

README.md
This is the doc review of https://github.com/ballerina-platform/lsp4intellij/pull/33.
> Link to the PR for changes to the …
=> Review timeouts API documentation

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java, src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPIconProvider.java, src/main/java/org/wso2/lsp4intellij/contributors/symbol/LSPNavigationItem.java, src/main/java/org/wso2/lsp4intellij/contributors/symbol/LSPSymbolContributor.java, src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java
Add symbol support with minimum set of icon types that are commonly used.
=> Add LSPSymbolContributor for showing symbols from LSP client

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
This PR adds few bug fixes and improvements.
Fixes #28 partially.
=> Add bug fixes and improve stability

README.md
This PR fixes some highlighing and code formatting issues in README.md
=> Fix highlighting issues

src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/ServerStatus.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java, src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java, src/main/java/org/wso2/lsp4intellij/requests/FileEventManager.java
With this change we will not allow any request to be send to server until the Initialized request is sent. This make this library to work well with a LS which follows the Spec 3. The name of the new status is not ideal, please feel free to suggest new name if required.
=> Support for LSP Spec 3 initialized request handling

README.md
=> Fix Travis build URL

gradle.properties
=> Merge 0.9.0 release branch

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/ServerListener.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/MessageHandler.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/requests/Timeout.java
Fixes #56 and adds minor refactoring.
=> Fix timeouts API

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
This PR adds few text edits related improvements and fixes.
=> Add minor fixes

src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java
Fixes https://github.com/ballerina-platform/lsp4intellij/issues/65
=> Fix NPE in symbol provider when there are no LS started.

src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
Fix https://github.com/ballerina-platform/lsp4intellij/issues/68
=> Fix NPE when opening attached source files

src/main/java/org/wso2/lsp4intellij/contributors/LSPCompletionContributor.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
A NPE is thrown when typing the commit message in commit dialog due to
LS client trying to resolve the dummy file uri to a EditorEventManager
Fix for https://github.com/ballerina-platform/lsp4intellij/issues/48
=> Fix NPE in commit dialog

src/main/java/org/wso2/lsp4intellij/client/ClientContext.java, src/main/java/org/wso2/lsp4intellij/client/ServerWrapperBaseClientContext.java
Fix for https://github.com/ballerina-platform/lsp4intellij/issues/79
=> Expose project and RequestManager bound to current language client

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
=> Add getter for didChange parameters

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
=> Add fix for nullable text edits

.travis.yml
This PR fixes Travis build failure by add  necessary jdk configuration.
=> Fix travis build failure

src/test/java/org/wso2/lsp4intellij/utils/UtilsTest.java
Hi,
I've analysed your code base and noticed that `org.wso2.lsp4intellij.utils.Utils` is not fully tested.
I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
> Add unit tests for `org.wso2.lsp4intellij.utils.Utils`
> Improve coverage
> JDK 8
Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.
After inspection of this class I believe that your `arrayToString` method is probably not functioning as expected but is not used.
=> Add unit tests for org.wso2.lsp4intellij.utils.Utils

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Update gradle wrapper and dependency versions

src/test/java/org/wso2/lsp4intellij/utils/UtilsTest.java
This PR fixes the Travis build failure due to a missing license header.
=> Fix license issue

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
This PR adds a minor inspection related fix.
=> Fix inspections

gradle.properties
=> Merge 0.91.0 release branch

src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
=> Fix disposed project issue when shutting down language server

src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameHandler.java
=> Add minor fix for renaming support

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
=> Add signature help support

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/actions/LSPReformatAction.java, src/main/java/org/wso2/lsp4intellij/actions/LSPShowReformatDialogAction.java, src/main/java/org/wso2/lsp4intellij/contributors/inspection/LSPInspection.java, src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameHandler.java, src/main/java/org/wso2/lsp4intellij/requests/FileEventManager.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java, src/test/java/org/wso2/lsp4intellij/utils/FileUtilsTest.java
=> Improve file event handling

src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameHandler.java
This PR adds a minor fix related to renaming support.
=> Add minor fix

build.gradle, src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameHandler.java, src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameProcessor.java, src/test/java/org/wso2/lsp4intellij/utils/FileUtilsTest.java
This PR adds refactoring and gradle build related fixes for IntelliJ 2019.2 API.
Partially fixes #119.
=> [IntelliJ Plugin] Fix compatibility issues for IDEA 2019.2

src/main/java/org/wso2/lsp4intellij/contributors/LSPCompletionContributor.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
This PR adds minor improvements for completion implementation and `EditorEventManager`.
=> Improve completion and refactor code

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/editor/listeners/LSPEditorListener.java, src/main/java/org/wso2/lsp4intellij/editor/listeners/LSPFileDocumentManagerListener.java, src/main/java/org/wso2/lsp4intellij/editor/listeners/LSPFileEventManager.java, src/main/java/org/wso2/lsp4intellij/editor/listeners/VFSListener.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
=> Add support to preserve language connections when renaming/ moving connected files

src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
This PR removes usage of Guava (Google commons) library from lsp4intellij code.
Closes #126 and all future problems with guava versions inconsistency
=> Drop guava methods

README.md, src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/extensions/LSPExtensionManager.java, src/main/java/org/wso2/lsp4intellij/listeners/DocumentListenerImpl.java, src/main/java/org/wso2/lsp4intellij/listeners/EditorMouseListenerImpl.java, src/main/java/org/wso2/lsp4intellij/listeners/EditorMouseMotionListenerImpl.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPEditorListener.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPFileDocumentManagerListener.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPListener.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPProjectManagerListener.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPTypedHandler.java, src/main/java/org/wso2/lsp4intellij/listeners/VFSListener.java
This PR fixes the issue of LSP status widget not being disposed when a new project is opened in the same project window.
Partially fixes #118.
=> Improve status widget handling and add few other minor improvements

gradle.properties
=> Merge 0.93.0 release branch

src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPProjectManagerListener.java
=> Fix NPEs in LSP project event listener and completion icon provider 

src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
$subject. This error can be continuously observed for files with large number of errors(diagnostics annotations).
> Link to the …
=> Fix fatal error due to disposed editors

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
Change how the URL to file is processed with the help of IntelliJ IDEA
util classes so that the URL is IntelliJ IDEA friendly. This is really
needed for opening files which are inside archive files such as jar
files.
The previous implementation didn't support opening files inside jar files such as opening source code from source jar.
=> Improve symbol navigation

src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java
Update the file notifications according to the discussion done here
https://github.com/Microsoft/language-server-protocol/issues/60. Some
of the language servers depends on this. For example STS4
=> Fix not sending didChangeWatchedFiles for open document.

src/main/java/org/wso2/lsp4intellij/client/languageserver/ServerOptions.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
This PR revamps the code actions implementation, which also resolves a critical performance issue related to diagnostics. Now instead of fetching code actions on each document change, code actions requests are sent only when user places the cursor on the diagnostic or on a line. Therefore this also adds #137.
=> Revamp code action implementation

src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java
Fix NPE when symbol file are null due to LS symbol errors. Some time some LS send the symbol info but they are outdated. For example after a file rename the symbol in the symbol cache become stale. Due to this the file becomes null.
=> Fix NPE when symbol file are null due to LS symbol errors.

src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java
Some language server depends on watched files event to update their
symbol indexes. Therefore when the files are renamed that must be
notified to the language server.
=> Send a DidChangeWatchedFiles event when the files are renamed

build.gradle, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/RequestManager.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
Upgrade the library code to support latest lsp4j so that support for
latest LSP spec can be added. Also fixed some possible NPEs
=> Add support for latest LSP4J 0.8.1

src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
This PR adds code snippet support (i.e intellij live templates).
Fixes #101.
=> Add LSP snippet (intellij live templates) support

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
=> Fix code actions NPE

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java
=> Fix potential memory leak in IntellijLanguageClient

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
This PR adds a fix for for invalid source navigation(goto definition) for the files which have `Tab` characters included. 
> Link …
=> Add fix for invalid source navigation when tab characters are present

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPProjectManagerListener.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
=> Fix langserver connections are not being initialized for already opened editors at IDE startup

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
This PR adds fix for invalid position navigation(when goto definition) in some contexts and also fixes #171.
> Link to the PR for …
=> Fix invalid source navigation and fatal error in IDEA 2019.3

gradle.properties
=> Merge 0.94.0 release branch

src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/extensions/LSPExtensionManager.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPCaretListenerImpl.java
This PR introduces minor improvements and fixes related to latest code actions related changes.
=> Improve code action implementation

src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java
$subject.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/21170.
> Link to the PR for changes to the training …
=> Fix implementation for "window/showMessage" notifications

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
=> Add minor fix for live template generation

src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/ProcessBuilderServerDefinition.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java
This PR,
- fixes fatal error due to a redundant listener dispose event.
- adds minor fix to process builder server definition implementation.
- adds minor refactoring for client API.
=> Add minor fixes and refactor code

src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
=> Avoid NPE in isWillSaveWaitUntil

src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java
Provide compatibility for both new and old IJ versions.
Fix for #190
=> Fixed compatibility issues with upcoming IJ release

build.gradle, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/RequestManager.java
=> upgrade with backward compat to lsp4j 0.9.0

src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
Fixes more NPEs due to nullable Boolean values from lsp4j.
Side note - is assuming `false` as the default ok in these cases? Or is this actually a bug with us not initializing the fields correctly?
=> Fix NPEs in DefaultRequestManager

build.gradle, spotbugs-exclude.xml, src/main/java/org/wso2/lsp4intellij/client/ClientContext.java, src/main/java/org/wso2/lsp4intellij/client/ServerWrapperBaseClientContext.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/contributors/fixes/LSPCodeActionFix.java, src/main/java/org/wso2/lsp4intellij/contributors/fixes/LSPCommandFix.java, src/main/java/org/wso2/lsp4intellij/contributors/psi/LSPPsiElement.java, src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameProcessor.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManagerBase.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java, src/main/java/org/wso2/lsp4intellij/utils/Utils.java
This PR 
- adds spotbugs plugin
- fixes all high-priority spotbugs warnings
- refactor code and fix few potential NPEs
> Link to …
=> Add spotbugs plugin and improve code

.github/workflows/main.yml
Add a crosspaltorm (windows/mac/ubuntu) crossjava (8, 11) CI via GitHub Actions.
Disable travis, move to shiny GA :)
Based on bsl-language-server approach and https://github.com/1c-syntax/bsl-language-server/blob/develop/.github/workflows/gradle.yml
=> Add multiplatform GA testing

.github/workflows/qa.yml, build.gradle
Add gradle config and GA-workflow for sonarcloud analysis.
Based on https://github.com/1c-syntax/bsl-language-server configuration
=> Add sonarcloud scan

src/main/java/org/wso2/lsp4intellij/client/DefaultLanguageClient.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
This PR fixes several issues encountered by me as described in the commits. It fixes issues #212, #211, #209, #213
=> Fix multiple bugs and extends capabilities

.github/workflows/main.yml, build.gradle, src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java, src/test/java/org/wso2/lsp4intellij/utils/FileUtilsTest.java, src/test/java/org/wso2/lsp4intellij/utils/UtilsTest.java
This PR resolves unit test failures after enabling jdk11 build.
> Link to the PR for changes to the training content in …
=> Fix build failures

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: 
fix #217 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
=> fix-error of calculating lsp position

src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPIconProvider.java, src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java
Some language server integration needs adding more icon information than the symbol kind based on the symbol information. The new method in IconProvider will enable such implementation to provide more detailed icons based on the symbol information.
=> Enhance support for symbol icons

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
this fixes some concurrency/blocking problem which occured in our testing.
fixes #226
=> Concurrency fixes

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/requests/HoverHandler.java
this PR fixes some minor issues regarding hovers 
possibly fixes #103
=> Hover fixes

src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
this PR adds the ability to do a restart of the Languageserver from the ui as well as some refactorings
i exposed the "gotoLocation"-Method in EditorEventManager  as i want to use it in my own plugin and also think it's generally useful.
=> Refactorings

src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
=> fix those lspoutofbounds

src/main/java/org/wso2/lsp4intellij/requests/HoverHandler.java
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> make hover more readable in darkmode

src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
see headline.
If someone has a better idea on fixing this, I'm open for ideas...
possibly fixes #100
=> dont let hovers run over whole screen (just this one dirty trick...)

src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> fix null pointer

src/main/java/org/wso2/lsp4intellij/client/languageserver/LSPServerStatusWidget.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/editor/DocumentEventManager.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
Some problems are found in using the plugin
1. using the deprecated method
2. there exist some NPE problems 
3. some fields and method declared by `protected` will be easy to expand
=> fixing some minor issues

.github/workflows/main.yml
$subject since java 8 will not be supported in latest intellij platform SDKs.
> Link to the PR for changes to the training …
=> Remove JDK 8 checks from CI build

src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: 
Fix possible null pointers in DefaultRequestManager.java. 
Also fixes: https://github.com/ballerina-platform/lsp4intellij/issues/255
=> fix null pointers

src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPProjectManagerListener.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves NullPointerException. Issue: https://github.com/ballerina-platform/lsp4intellij/issues/254
Check for null before dereferencing LanguageServerWrapper
=> check for null before dereferencing LanguageServerWrapper

build.gradle, src/main/java/org/wso2/lsp4intellij/client/languageserver/ServerOptions.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/RequestManager.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java, src/main/java/org/wso2/lsp4intellij/contributors/symbol/WorkspaceSymbolProvider.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/requests/WorkspaceEditHandler.java, src/main/java/org/wso2/lsp4intellij/utils/DocumentUtils.java
The upgrade is done by adapting new APIs to previous IJ implementations.
Update to latest lsp4j version to support latest LSP spec.
Able to use with newer LS versions
=> Update to latest LSP

jitpack.yml
Closes: #297 
Make jitpack work again 
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Target jitpack to jdk11

README.md
I believe this is cleaner. Feel free to close if you disagree.
* no JavaDoc
* no versioning details
* no mention of deprecated stuff
* fixed a typo
=> Leaner documentation

build.gradle, gradle.properties
=> Merge release branch with master 

spotbugs-exclude.xml, src/main/java/org/wso2/lsp4intellij/IntellijLanguageClient.java, src/main/java/org/wso2/lsp4intellij/client/connection/ProcessStreamConnectionProvider.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/serverdefinition/LanguageServerDefinition.java, src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/MessageHandler.java, src/main/java/org/wso2/lsp4intellij/listeners/DocumentListenerImpl.java, src/main/java/org/wso2/lsp4intellij/listeners/EditorMouseListenerImpl.java, src/main/java/org/wso2/lsp4intellij/listeners/EditorMouseMotionListenerImpl.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPCaretListenerImpl.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPFileDocumentManagerListener.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPFileEventManager.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPTypedHandler.java, src/main/java/org/wso2/lsp4intellij/requests/HoverHandler.java, src/main/java/org/wso2/lsp4intellij/requests/Timeout.java, src/main/java/org/wso2/lsp4intellij/requests/WorkspaceEditHandler.java, src/main/java/org/wso2/lsp4intellij/statusbar/LSPServerStatusWidgetFactory.java, src/main/java/org/wso2/lsp4intellij/utils/FileUtils.java, src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java, src/main/java/org/wso2/lsp4intellij/utils/Utils.java
This PR fixes some of the code level warnings shown with java 11
> Link to the PR for changes to the training content in …
=> Fix code warnings for java 11

gradle.properties
=> Sync master after the release 0.96.0

src/main/java/org/wso2/lsp4intellij/client/languageserver/requestmanager/DefaultRequestManager.java, src/main/java/org/wso2/lsp4intellij/contributors/LSPCompletionContributor.java, src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java, src/main/java/org/wso2/lsp4intellij/contributors/rename/LSPRenameHandler.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java, src/main/java/org/wso2/lsp4intellij/editor/EditorEventManagerBase.java, src/main/java/org/wso2/lsp4intellij/listeners/LSPCaretListenerImpl.java, src/main/java/org/wso2/lsp4intellij/requests/WorkspaceEditHandler.java, src/main/java/org/wso2/lsp4intellij/statusbar/LSPServerStatusWidget.java, src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
Following bugs were fixed in this PR.
- Fixed an issue where renaming elements across multiple files was not functioning properly. (Related to https://github.com/ballerina-platform/lsp4intellij/issues/359)
- Resolved a problem where parameter information was not displayed in signature help. (Related to https://github.com/ballerina-platform/lsp4intellij/issues/360)
Additionally, this PR introduces more null checks and enhancements to the logic for displaying code actions, improving upon the previous version.
- For the renaming issue, implemented LSP renaming support and added a new function to obtain an edits runnable object, which applies changes across multiple files.
- For the signature help issue, added logic to extract parameter information from responses and implemented proper …
=> Bug fixes for lsp4intellij version 0.96.0

gradle.properties
=> Sync release branch with master

src/main/java/org/wso2/lsp4intellij/contributors/icon/LSPDefaultIconProvider.java
$subject. Related to https://github.com/ballerina-platform/lsp4intellij/issues/367
Following screenshot contains the icon used as a default option.
=> Add default icon for completions

src/main/java/org/wso2/lsp4intellij/utils/GUIUtils.java
$subject. This address the issue https://github.com/ballerina-platform/lsp4intellij/issues/368
*After adding a small padding*
=> Add padding to hover content

src/main/java/org/wso2/lsp4intellij/editor/EditorEventManager.java
Fixes https://github.com/ballerina-platform/lsp4intellij/issues/371
Updated the regex pattern to match nested braces as well.
=> Fix incorrect code snippets issue

src/main/java/org/wso2/lsp4intellij/client/languageserver/wrapper/LanguageServerWrapper.java
Fixes https://github.com/ballerina-platform/lsp4intellij/issues/372
=> Fix client connection issue

.github/workflows/main.yml
$subject to fix build failures due to depreciated GH action version
> Link to the PR for changes to the training content in …
=> Update upload-artifact action version

src/main/java/org/wso2/lsp4intellij/contributors/annotator/LSPAnnotator.java
=>  Fix LSPAnnotator crash when diagnostics have no defined severity
